export default {
  login: "Abuzar444",
  id: 84353190,
  node_id: "MDQ6VXNlcjg0MzUzMTkw",
  avatar_url: "https://avatars.githubusercontent.com/u/84353190?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Abuzar444",
  html_url: "https://github.com/Abuzar444",
  followers_url: "https://api.github.com/users/Abuzar444/followers",
  following_url: "https://api.github.com/users/Abuzar444/following{/other_user}",
  gists_url: "https://api.github.com/users/Abuzar444/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Abuzar444/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Abuzar444/subscriptions",
  organizations_url: "https://api.github.com/users/Abuzar444/orgs",
  repos_url: "https://api.github.com/users/Abuzar444/repos",
  events_url: "https://api.github.com/users/Abuzar444/events{/privacy}",
  received_events_url: "https://api.github.com/users/Abuzar444/received_events",
  type: "User",
  site_admin: false,
  name: "Abuzar Dawar",
  company: null,
  blog: "",
  location: "Rawalpindi Pakistan",
  email: null,
  hireable: null,
  bio: "Studying Software Engineering, learning  HTML, CSS & javaScript, ReactJS",
  twitter_username: "dawar_ab",
  public_repos: 44,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2021-05-17T21:17:24Z",
  updated_at: "2022-11-23T03:49:58Z"
}